// resources/js/Pages/Admin/Email/Index.vue
<script setup>
import { ref, computed } from 'vue'
import { Head, useForm } from '@inertiajs/vue3'
import AdminLayout from '@/Layouts/AdminLayout.vue'

const props = defineProps({
  recipients: { type: Array, default: () => [] },
  stats: { type: Object, default: () => ({ total_recipients: 0 }) }
})

const selected = ref([])

const bulkForm = useForm({
  user_ids: [],
  subject: '',
  html_content: '',
  text_content: ''
})

const promoForm = useForm({
  subject: '',
  html_content: '',
  text_content: ''
})

const testForm = useForm({
  email: '',
  subject: '',
  html_content: '',
  text_content: ''
})

const allSelected = computed(() => props.recipients.length > 0 && selected.value.length === props.recipients.length)

const toggleAll = (checked) => {
  selected.value = checked ? props.recipients.map(r => r.id) : []
}

const toggleRecipient = (id, checked) => {
  if (checked) {
    if (!selected.value.includes(id)) selected.value.push(id)
  } else {
    selected.value = selected.value.filter(x => x !== id)
  }
}

const submitBulk = () => {
  bulkForm.user_ids = selected.value
  bulkForm.post(route('admin.email.bulk'), {
    onSuccess: () => {
      selected.value = []
      bulkForm.reset()
    }
  })
}

const submitPromo = () => {
  promoForm.post(route('admin.email.promotional-campaign'), {
    onSuccess: () => promoForm.reset()
  })
}

const submitTest = () => {
  testForm.post(route('admin.email.test'), {
    onSuccess: () => testForm.reset()
  })
}
</script>

<template>
  <AdminLayout>
    <div class="max-w-6xl mx-auto py-10 space-y-8">
      <Head title="Email Management" />

      <header>
        <h1 class="text-3xl font-bold">Email Management</h1>
        <p class="text-muted-foreground">Send bulk, campaign, and test emails.</p>
      </header>

    <section class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <div class="bg-card border border-border rounded-lg p-4">
        <p class="text-sm text-muted-foreground">Total recipients</p>
        <p class="text-3xl font-bold">{{ stats.total_recipients ?? 0 }}</p>
      </div>
    </section>

    <section class="grid gap-6 lg:grid-cols-2">
      <div class="bg-card border border-border rounded-lg p-6 space-y-4">
        <div>
          <h2 class="text-xl font-semibold">Bulk Email</h2>
          <p class="text-muted-foreground text-sm">Send to selected users</p>
        </div>

        <div class="space-y-2">
          <div class="flex items-center space-x-2">
            <input id="select-all" type="checkbox" :checked="allSelected" @change="e => toggleAll(e.target.checked)" />
            <label for="select-all" class="text-sm">Select all ({{ recipients.length }})</label>
            <span class="text-xs text-muted-foreground">{{ selected.length }} selected</span>
          </div>
          <div class="max-h-48 overflow-y-auto border rounded p-2 space-y-2">
            <div v-for="user in recipients" :key="user.id" class="flex items-center space-x-2">
              <input
                :id="`user-${user.id}`"
                type="checkbox"
                :checked="selected.includes(user.id)"
                @change="e => toggleRecipient(user.id, e.target.checked)"
              />
              <label :for="`user-${user.id}`" class="text-sm">{{ user.name }} ({{ user.email }})</label>
            </div>
            <p v-if="recipients.length === 0" class="text-sm text-muted-foreground">No recipients available.</p>
          </div>
        </div>

        <form class="space-y-3" @submit.prevent="submitBulk">
          <div>
            <label class="text-sm font-medium" for="bulk-subject">Subject</label>
            <input id="bulk-subject" v-model="bulkForm.subject" class="w-full border rounded px-3 py-2" required />
          </div>
          <div>
            <label class="text-sm font-medium" for="bulk-html">HTML Content</label>
            <textarea id="bulk-html" v-model="bulkForm.html_content" rows="4" class="w-full border rounded px-3 py-2" required />
          </div>
          <div>
            <label class="text-sm font-medium" for="bulk-text">Plain Text (optional)</label>
            <textarea id="bulk-text" v-model="bulkForm.text_content" rows="3" class="w-full border rounded px-3 py-2" />
          </div>
          <button type="submit" class="w-full bg-primary text-primary-foreground rounded px-4 py-2" :disabled="selected.length === 0 || bulkForm.processing">
            {{ bulkForm.processing ? 'Sending…' : 'Send Bulk Email' }}
          </button>
        </form>
      </div>

      <div class="bg-card border border-border rounded-lg p-6 space-y-4">
        <div>
          <h2 class="text-xl font-semibold">Promotional Campaign</h2>
          <p class="text-muted-foreground text-sm">Send to all recipients</p>
        </div>

        <form class="space-y-3" @submit.prevent="submitPromo">
          <div>
            <label class="text-sm font-medium" for="promo-subject">Subject</label>
            <input id="promo-subject" v-model="promoForm.subject" class="w-full border rounded px-3 py-2" required />
          </div>
          <div>
            <label class="text-sm font-medium" for="promo-html">HTML Content</label>
            <textarea id="promo-html" v-model="promoForm.html_content" rows="5" class="w-full border rounded px-3 py-2" required />
          </div>
          <div>
            <label class="text-sm font-medium" for="promo-text">Plain Text (optional)</label>
            <textarea id="promo-text" v-model="promoForm.text_content" rows="3" class="w-full border rounded px-3 py-2" />
          </div>
          <button type="submit" class="w-full bg-primary text-primary-foreground rounded px-4 py-2" :disabled="promoForm.processing">
            {{ promoForm.processing ? 'Sending…' : 'Send Campaign to All' }}
          </button>
        </form>
      </div>
    </section>

    <section class="bg-card border border-border rounded-lg p-6 space-y-4">
      <div>
        <h2 class="text-xl font-semibold">Send Test Email</h2>
        <p class="text-muted-foreground text-sm">Send a single test to verify delivery</p>
      </div>

      <form class="grid gap-4 md:grid-cols-2" @submit.prevent="submitTest">
        <div class="space-y-2">
          <label class="text-sm font-medium" for="test-email">Email</label>
          <input id="test-email" type="email" v-model="testForm.email" class="w-full border rounded px-3 py-2" required />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium" for="test-subject">Subject</label>
          <input id="test-subject" v-model="testForm.subject" class="w-full border rounded px-3 py-2" required />
        </div>
        <div class="space-y-2 md:col-span-2">
          <label class="text-sm font-medium" for="test-html">HTML Content</label>
          <textarea id="test-html" v-model="testForm.html_content" rows="4" class="w-full border rounded px-3 py-2" required />
        </div>
        <div class="space-y-2 md:col-span-2">
          <label class="text-sm font-medium" for="test-text">Plain Text (optional)</label>
          <textarea id="test-text" v-model="testForm.text_content" rows="3" class="w-full border rounded px-3 py-2" />
        </div>
        <button type="submit" class="bg-primary text-primary-foreground rounded px-4 py-2 md:col-span-2" :disabled="testForm.processing">
          {{ testForm.processing ? 'Sending…' : 'Send Test Email' }}
        </button>
      </form>
    </section>
    </div>
  </AdminLayout>
</template>

// resources/js/Pages/Admin/Email/Index.jsx
import React, { useState } from 'react';
import { Head, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Textarea } from '@/Components/ui/textarea';
import { Checkbox } from '@/Components/ui/checkbox';
import { Badge } from '@/Components/ui/badge';
import { toast } from 'sonner';

export default function Index({ recipients, stats }) {
    const [selected, setSelected] = useState([]);

    const bulkForm = useForm({
        user_ids: [],
        subject: '',
        html_content: '',
        text_content: '',
    });

    const promoForm = useForm({
        subject: '',
        html_content: '',
        text_content: '',
    });

    const testForm = useForm({
        email: '',
        subject: '',
        html_content: '',
        text_content: '',
    });

    const toggleRecipient = (id, checked) => {
        setSelected(prev => checked ? [...prev, id] : prev.filter(x => x !== id));
    };

    const toggleAll = (checked) => {
        setSelected(checked ? recipients.map(r => r.id) : []);
    };

    const submitBulk = (e) => {
        e.preventDefault();
        bulkForm.setData('user_ids', selected);
        bulkForm.post(route('admin.email.bulk'), {
            onSuccess: () => {
                toast.success('Bulk email sent');
                bulkForm.reset();
                setSelected([]);
            },
            onError: () => toast.error('Failed to send bulk email'),
        });
    };

    const submitPromo = (e) => {
        e.preventDefault();
        promoForm.post(route('admin.email.promotional-campaign'), {
            onSuccess: () => {
                toast.success('Promotional campaign sent');
                promoForm.reset();
            },
            onError: () => toast.error('Failed to send campaign'),
        });
    };

    const submitTest = (e) => {
        e.preventDefault();
        testForm.post(route('admin.email.test'), {
            onSuccess: () => {
                toast.success('Test email sent');
                testForm.reset();
            },
            onError: () => toast.error('Failed to send test email'),
        });
    };

    return (
        <AdminLayout>
            <Head title="Email Management" />

            <div className="space-y-6">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Email Management</h1>
                    <p className="text-muted-foreground">Send bulk, campaign, and test emails via Brevo/SMTP.</p>
                </div>

                {/* Stats */}
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Total recipients</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{stats?.total_recipients ?? 0}</div>
                            <p className="text-xs text-muted-foreground">Users with valid email addresses</p>
                        </CardContent>
                    </Card>
                </div>

                <div className="grid gap-6 lg:grid-cols-2">
                    {/* Bulk Email */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Bulk Email</CardTitle>
                            <CardDescription>Send to selected users</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <form onSubmit={submitBulk} className="space-y-4">
                                <div className="space-y-2">
                                    <Label>Select Recipients ({selected.length} selected)</Label>
                                    <div className="flex items-center space-x-2">
                                        <Checkbox
                                            id="select-all"
                                            checked={selected.length === recipients.length && recipients.length > 0}
                                            onCheckedChange={toggleAll}
                                        />
                                        <Label htmlFor="select-all">Select All</Label>
                                        <Badge variant="secondary">{recipients.length} available</Badge>
                                    </div>
                                    <div className="max-h-48 overflow-y-auto border rounded p-2 space-y-2">
                                        {recipients.map((user) => (
                                            <div key={user.id} className="flex items-center space-x-2">
                                                <Checkbox
                                                    id={`user-${user.id}`}
                                                    checked={selected.includes(user.id)}
                                                    onCheckedChange={(checked) => toggleRecipient(user.id, checked)}
                                                />
                                                <Label htmlFor={`user-${user.id}`} className="text-sm">
                                                    {user.name} ({user.email})
                                                </Label>
                                            </div>
                                        ))}
                                        {recipients.length === 0 && (
                                            <p className="text-sm text-muted-foreground">No recipients available.</p>
                                        )}
                                    </div>
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="bulk-subject">Subject</Label>
                                    <Input
                                        id="bulk-subject"
                                        value={bulkForm.data.subject}
                                        onChange={(e) => bulkForm.setData('subject', e.target.value)}
                                        placeholder="Enter subject"
                                        required
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="bulk-html">HTML Content</Label>
                                    <Textarea
                                        id="bulk-html"
                                        value={bulkForm.data.html_content}
                                        onChange={(e) => bulkForm.setData('html_content', e.target.value)}
                                        rows={5}
                                        required
                                        placeholder="<p>Your message...</p>"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="bulk-text">Plain Text (optional)</Label>
                                    <Textarea
                                        id="bulk-text"
                                        value={bulkForm.data.text_content}
                                        onChange={(e) => bulkForm.setData('text_content', e.target.value)}
                                        rows={3}
                                        placeholder="Optional plain text version"
                                    />
                                </div>

                                <Button
                                    type="submit"
                                    disabled={selected.length === 0 || bulkForm.processing}
                                    className="w-full"
                                >
                                    {bulkForm.processing ? 'Sending...' : 'Send Bulk Email'}
                                </Button>
                            </form>
                        </CardContent>
                    </Card>

                    {/* Promotional Campaign */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Promotional Campaign</CardTitle>
                            <CardDescription>Send to all recipients</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <form onSubmit={submitPromo} className="space-y-4">
                                <div className="space-y-2">
                                    <Label htmlFor="promo-subject">Subject</Label>
                                    <Input
                                        id="promo-subject"
                                        value={promoForm.data.subject}
                                        onChange={(e) => promoForm.setData('subject', e.target.value)}
                                        placeholder="Enter subject"
                                        required
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="promo-html">HTML Content</Label>
                                    <Textarea
                                        id="promo-html"
                                        value={promoForm.data.html_content}
                                        onChange={(e) => promoForm.setData('html_content', e.target.value)}
                                        rows={5}
                                        required
                                        placeholder="<p>Your campaign message...</p>"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="promo-text">Plain Text (optional)</Label>
                                    <Textarea
                                        id="promo-text"
                                        value={promoForm.data.text_content}
                                        onChange={(e) => promoForm.setData('text_content', e.target.value)}
                                        rows={3}
                                        placeholder="Optional plain text version"
                                    />
                                </div>

                                <Button
                                    type="submit"
                                    disabled={promoForm.processing}
                                    className="w-full"
                                >
                                    {promoForm.processing ? 'Sending...' : 'Send Campaign to All'}
                                </Button>
                            </form>
                        </CardContent>
                    </Card>
                </div>

                {/* Test Email */}
                <Card>
                    <CardHeader>
                        <CardTitle>Send Test Email</CardTitle>
                        <CardDescription>Send a single test to verify delivery</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={submitTest} className="grid gap-4 md:grid-cols-2">
                            <div className="space-y-2">
                                <Label htmlFor="test-email">Email</Label>
                                <Input
                                    id="test-email"
                                    type="email"
                                    value={testForm.data.email}
                                    onChange={(e) => testForm.setData('email', e.target.value)}
                                    required
                                    placeholder="recipient@example.com"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="test-subject">Subject</Label>
                                <Input
                                    id="test-subject"
                                    value={testForm.data.subject}
                                    onChange={(e) => testForm.setData('subject', e.target.value)}
                                    required
                                    placeholder="Test subject"
                                />
                            </div>
                            <div className="space-y-2 md:col-span-2">
                                <Label htmlFor="test-html">HTML Content</Label>
                                <Textarea
                                    id="test-html"
                                    value={testForm.data.html_content}
                                    onChange={(e) => testForm.setData('html_content', e.target.value)}
                                    rows={4}
                                    required
                                    placeholder="<p>Hello!</p>"
                                />
                            </div>
                            <div className="space-y-2 md:col-span-2">
                                <Label htmlFor="test-text">Plain Text (optional)</Label>
                                <Textarea
                                    id="test-text"
                                    value={testForm.data.text_content}
                                    onChange={(e) => testForm.setData('text_content', e.target.value)}
                                    rows={3}
                                    placeholder="Optional plain text version"
                                />
                            </div>
                            <Button type="submit" disabled={testForm.processing} className="md:col-span-2">
                                {testForm.processing ? 'Sending...' : 'Send Test Email'}
                            </Button>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AdminLayout>
    );
}
