// resources/js/Pages/Admin/Sms/Index.vue
<script setup>
import { ref } from 'vue'
import { Head, useForm } from '@inertiajs/vue3'
import AdminLayout from '@/Layouts/AdminLayout.vue'

const props = defineProps({
  usersWithPhones: { type: Array, default: () => [] },
  stats: { type: Object, default: () => ({ total_users_with_phones: 0 }) }
})

const selected = ref([])

const customForm = useForm({
  user_ids: [],
  message: ''
})

const paymentForm = useForm({
  movie_title: '',
  amount: ''
})

const renewalForm = useForm({
  movie_title: '',
  days_remaining: ''
})

const toggleAll = (checked) => {
  selected.value = checked ? props.usersWithPhones.map(u => u.id) : []
}

const toggleUser = (id, checked) => {
  if (checked) {
    if (!selected.value.includes(id)) selected.value.push(id)
  } else {
    selected.value = selected.value.filter(x => x !== id)
  }
}

const submitCustom = () => {
  customForm.user_ids = selected.value
  customForm.post(route('admin.sms.custom'), {
    onSuccess: () => {
      selected.value = []
      customForm.reset()
    }
  })
}

const submitPayment = () => {
  paymentForm.post(route('admin.sms.payment-notifications'), {
    onSuccess: () => paymentForm.reset()
  })
}

const submitRenewal = () => {
  renewalForm.post(route('admin.sms.renewal-reminders'), {
    onSuccess: () => renewalForm.reset()
  })
}
</script>

<template>
  <AdminLayout>
    <div class="max-w-6xl mx-auto py-10 space-y-8">
      <Head title="SMS Management" />

      <header>
        <h1 class="text-3xl font-bold">SMS Management</h1>
        <p class="text-muted-foreground">Send bulk SMS notifications to your users.</p>
      </header>

    <section class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      <div class="bg-card border border-border rounded-lg p-4">
        <p class="text-sm text-muted-foreground">Users with phones</p>
        <p class="text-3xl font-bold">{{ stats.total_users_with_phones ?? 0 }}</p>
      </div>
    </section>

    <section class="grid gap-6 md:grid-cols-2">
      <div class="bg-card border border-border rounded-lg p-6 space-y-4">
        <div>
          <h2 class="text-xl font-semibold">Send Custom SMS</h2>
          <p class="text-sm text-muted-foreground">Send a custom message to selected users</p>
        </div>

        <div class="space-y-2">
          <div class="flex items-center space-x-2">
            <input id="select-all" type="checkbox" :checked="selected.length === usersWithPhones.length && usersWithPhones.length > 0" @change="e => toggleAll(e.target.checked)" />
            <label for="select-all" class="text-sm">Select all ({{ usersWithPhones.length }})</label>
            <span class="text-xs text-muted-foreground">{{ selected.length }} selected</span>
          </div>
          <div class="max-h-48 overflow-y-auto border rounded p-2 space-y-2">
            <div v-for="user in usersWithPhones" :key="user.id" class="flex items-center space-x-2">
              <input
                :id="`user-${user.id}`"
                type="checkbox"
                :checked="selected.includes(user.id)"
                @change="e => toggleUser(user.id, e.target.checked)"
              />
              <label :for="`user-${user.id}`" class="text-sm">{{ user.name }} ({{ user.phone_number }})</label>
            </div>
            <p v-if="usersWithPhones.length === 0" class="text-sm text-muted-foreground">No users with phone numbers.</p>
          </div>
        </div>

        <form class="space-y-3" @submit.prevent="submitCustom">
          <div>
            <label class="text-sm font-medium" for="message">Message (max 160 chars)</label>
            <textarea id="message" v-model="customForm.message" rows="3" maxlength="160" class="w-full border rounded px-3 py-2" required />
            <p class="text-xs text-muted-foreground">{{ customForm.message.length }}/160</p>
          </div>
          <button type="submit" class="w-full bg-primary text-primary-foreground rounded px-4 py-2" :disabled="selected.length === 0 || customForm.processing">
            {{ customForm.processing ? 'Sending…' : 'Send SMS' }}
          </button>
        </form>
      </div>

      <div class="bg-card border border-border rounded-lg p-6 space-y-6">
        <div>
          <h2 class="text-xl font-semibold">Payment Notifications</h2>
          <p class="text-sm text-muted-foreground">Send payment confirmation to all users with phones</p>
        </div>
        <form class="space-y-3" @submit.prevent="submitPayment">
          <div>
            <label class="text-sm font-medium" for="movie_title">Movie title</label>
            <input id="movie_title" v-model="paymentForm.movie_title" class="w-full border rounded px-3 py-2" required />
          </div>
          <div>
            <label class="text-sm font-medium" for="amount">Amount</label>
            <input id="amount" v-model="paymentForm.amount" type="number" min="0" step="0.01" class="w-full border rounded px-3 py-2" required />
          </div>
          <button type="submit" class="w-full bg-primary text-primary-foreground rounded px-4 py-2" :disabled="paymentForm.processing">
            {{ paymentForm.processing ? 'Sending…' : 'Send Payment Notifications' }}
          </button>
        </form>

        <div class="border-t border-border pt-4 space-y-2">
          <div class="flex items-center justify-between">
            <div>
              <h3 class="font-semibold">Renewal Reminders</h3>
              <p class="text-sm text-muted-foreground">Placeholder until subscription logic exists</p>
            </div>
          </div>
          <form class="space-y-3" @submit.prevent="submitRenewal">
            <div>
              <label class="text-sm font-medium" for="renewal-movie-title">Movie title</label>
              <input id="renewal-movie-title" v-model="renewalForm.movie_title" class="w-full border rounded px-3 py-2" required />
            </div>
            <div>
              <label class="text-sm font-medium" for="days_remaining">Days remaining</label>
              <input id="days_remaining" v-model="renewalForm.days_remaining" type="number" min="1" max="365" class="w-full border rounded px-3 py-2" required />
            </div>
            <button type="submit" class="w-full bg-muted text-foreground rounded px-4 py-2" :disabled="renewalForm.processing">
              {{ renewalForm.processing ? 'Submitting…' : 'Send Renewal Reminder' }}
            </button>
          </form>
        </div>
      </div>
    </section>
    </div>
  </AdminLayout>
</template>

// resources/js/Pages/Admin/Sms/Index.jsx
import React, { useState } from 'react';
import { Head } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { useForm } from '@inertiajs/react';
import { toast } from 'sonner';

export default function Index({ usersWithPhones, stats }) {
    const [selectedUsers, setSelectedUsers] = useState([]);

    const customSmsForm = useForm({
        user_ids: [],
        message: ''
    });

    const paymentForm = useForm({
        movie_title: '',
        amount: ''
    });

    const renewalForm = useForm({
        movie_title: '',
        days_remaining: ''
    });

    const handleUserSelect = (userId, checked) => {
        if (checked) {
            setSelectedUsers([...selectedUsers, userId]);
        } else {
            setSelectedUsers(selectedUsers.filter(id => id !== userId));
        }
    };

    const handleSelectAll = (checked) => {
        if (checked) {
            setSelectedUsers(usersWithPhones.map(user => user.id));
        } else {
            setSelectedUsers([]);
        }
    };

    const submitCustomSms = (e) => {
        e.preventDefault();
        customSmsForm.setData('user_ids', selectedUsers);
        customSmsForm.post(route('admin.sms.custom'), {
            onSuccess: () => {
                toast.success('SMS sent successfully!');
                customSmsForm.reset();
                setSelectedUsers([]);
            },
            onError: () => {
                toast.error('Failed to send SMS');
            }
        });
    };

    const submitPaymentNotifications = (e) => {
        e.preventDefault();
        paymentForm.post(route('admin.sms.payment-notifications'), {
            onSuccess: () => {
                toast.success('Payment notifications sent!');
                paymentForm.reset();
            },
            onError: () => {
                toast.error('Failed to send payment notifications');
            }
        });
    };

    const submitRenewalReminders = (e) => {
        e.preventDefault();
        renewalForm.post(route('admin.sms.renewal-reminders'), {
            onSuccess: () => {
                toast.success('Renewal reminders sent!');
                renewalForm.reset();
            },
            onError: () => {
                toast.error('Failed to send renewal reminders');
            }
        });
    };

    return (
        <AdminLayout>
            <Head title="SMS Management" />

            <div className="space-y-6">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">SMS Management</h1>
                    <p className="text-muted-foreground">
                        Send bulk SMS notifications to your users
                    </p>
                </div>

                {/* Stats */}
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Users with Phones
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{stats.total_users_with_phones}</div>
                        </CardContent>
                    </Card>
                </div>

                <div className="grid gap-6 md:grid-cols-2">
                    {/* Custom SMS */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Send Custom SMS</CardTitle>
                            <CardDescription>
                                Send a custom message to selected users
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <form onSubmit={submitCustomSms} className="space-y-4">
                                {/* User Selection */}
                                <div className="space-y-2">
                                    <Label>Select Recipients ({selectedUsers.length} selected)</Label>
                                    <div className="flex items-center space-x-2">
                                        <Checkbox
                                            id="select-all"
                                            checked={selectedUsers.length === usersWithPhones.length}
                                            onCheckedChange={handleSelectAll}
                                        />
                                        <Label htmlFor="select-all">Select All Users</Label>
                                    </div>
                                    <div className="max-h-40 overflow-y-auto border rounded p-2 space-y-2">
                                        {usersWithPhones.map((user) => (
                                            <div key={user.id} className="flex items-center space-x-2">
                                                <Checkbox
                                                    id={`user-${user.id}`}
                                                    checked={selectedUsers.includes(user.id)}
                                                    onCheckedChange={(checked) => handleUserSelect(user.id, checked)}
                                                />
                                                <Label htmlFor={`user-${user.id}`} className="text-sm">
                                                    {user.name} ({user.phone_number})
                                                </Label>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                {/* Message */}
                                <div className="space-y-2">
                                    <Label htmlFor="message">Message (max 160 characters)</Label>
                                    <Textarea
                                        id="message"
                                        value={customSmsForm.data.message}
                                        onChange={e => customSmsForm.setData('message', e.target.value)}
                                        placeholder="Enter your SMS message..."
                                        maxLength={160}
                                        rows={3}
                                    />
                                    <div className="text-sm text-muted-foreground">
                                        {customSmsForm.data.message.length}/160 characters
                                    </div>
                                </div>

                                <Button
                                    type="submit"
                                    disabled={selectedUsers.length === 0 || customSmsForm.processing}
                                    className="w-full"
                                >
                                    {customSmsForm.processing ? 'Sending...' : 'Send SMS'}
                                </Button>
                            </form>
                        </CardContent>
                    </Card>

                    {/* Payment Notifications */}
                    <Card>
                        <CardHeader>
                            <CardTitle>Payment Notifications</CardTitle>
                            <CardDescription>
                                Send payment confirmation to all users with phones
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <form onSubmit={submitPaymentNotifications} className="space-y-4">
                                <div className="space-y-2">
                                    <Label htmlFor="movie_title">Movie Title</Label>
                                    <Input
                                        id="movie_title"
                                        value={paymentForm.data.movie_title}
                                        onChange={e => paymentForm.setData('movie_title', e.target.value)}
                                        placeholder="Enter movie title"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="amount">Amount (₵)</Label>
                                    <Input
                                        id="amount"
                                        type="number"
                                        step="0.01"
                                        value={paymentForm.data.amount}
                                        onChange={e => paymentForm.setData('amount', e.target.value)}
                                        placeholder="0.00"
                                    />
                                </div>

                                <Button
                                    type="submit"
                                    disabled={paymentForm.processing}
                                    className="w-full"
                                >
                                    {paymentForm.processing ? 'Sending...' : 'Send Payment Notifications'}
                                </Button>
                            </form>
                        </CardContent>
                    </Card>
                </div>

                {/* Renewal Reminders */}
                <Card>
                    <CardHeader>
                        <CardTitle>Renewal Reminders</CardTitle>
                        <CardDescription>
                            Send renewal reminders to users (available when subscription system is implemented)
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={submitRenewalReminders} className="space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="renewal_movie_title">Movie Title</Label>
                                    <Input
                                        id="renewal_movie_title"
                                        value={renewalForm.data.movie_title}
                                        onChange={e => renewalForm.setData('movie_title', e.target.value)}
                                        placeholder="Enter movie title"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="days_remaining">Days Remaining</Label>
                                    <Input
                                        id="days_remaining"
                                        type="number"
                                        value={renewalForm.data.days_remaining}
                                        onChange={e => renewalForm.setData('days_remaining', e.target.value)}
                                        placeholder="7"
                                    />
                                </div>
                            </div>

                            <Button
                                type="submit"
                                disabled={renewalForm.processing}
                                variant="outline"
                                className="w-full"
                            >
                                {renewalForm.processing ? 'Sending...' : 'Send Renewal Reminders (Coming Soon)'}
                            </Button>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AdminLayout>
    );
}
